package com.hezijie.www.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "ITEM".
 */
@Entity(schema = "daowei")
public class Item {

    @Id(autoincrement = true)
    private Long id;
    private String item;

    @Generated
    public Item() {
    }

    public Item(Long id) {
        this.id = id;
    }

    @Generated
    public Item(Long id, String item) {
        this.id = id;
        this.item = item;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getItem() {
        return item;
    }

    public void setItem(String item) {
        this.item = item;
    }

}
